---
- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages in Red Hat
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Red Hat"
